import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class LeaseAgreementCreate {
  @ApiProperty()
  start_date: string;
  @ApiProperty()
  end_date: string;
  @ApiProperty()
  monthly_rent: string;
  @ApiProperty()
  status: string;
  @ApiProperty()
  property_id: number;
  @ApiProperty()
  tenant_id: number;
}

export class LeaseAgreement {
  @ApiProperty()
  id: number;
  @ApiProperty()
  start_date: string;
  @ApiProperty()
  end_date: string;
  @ApiProperty()
  monthly_rent: string;
  @ApiProperty()
  status: string;
  @ApiProperty()
  property_id: number;
  @ApiProperty()
  tenant_id: number;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
