import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class PropertyCreate {
  @ApiProperty()
  address: string;
  @ApiProperty()
  rent_amount: string;
  @ApiProperty()
  status: string;
  @ApiProperty()
  description: string;
}

export class Property {
  @ApiProperty()
  id: number;
  @ApiProperty()
  address: string;
  @ApiProperty()
  rent_amount: string;
  @ApiProperty()
  status: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
