import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class MaintenanceRequestCreate {
  @ApiProperty()
  request_date: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  status: string;
  @ApiProperty()
  property_id: number;
}

export class MaintenanceRequest {
  @ApiProperty()
  id: number;
  @ApiProperty()
  request_date: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  status: string;
  @ApiProperty()
  property_id: number;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
